version: "3.7"
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
    command: --quiet
    networks: 
      - internal
  migration:
    image: node:10.15.1
    command: node database/DatabaseScript.js
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - mongodb
    ports:
      - "3006:3006"
    networks: 
      - internal
  server:
    image: node:10.15.1
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - migration
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
    networks: 
      - internal
  frontend:
    image: node:10.15.1
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      HOST: 0.0.0.0
    networks: 
      - internal

networks:
  internal:
    external: false 
