name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Goto frontend
      run: cd frontend/
    - name: Install Dependencies
      run: npm install
    - name: Build Application
      run: npm run build
